### ISSUE TITLE
Error 403 when accessing Rewe API to get JSON

### ISSUE THREAD

**Issue by Nerbry72** [foo-git/rewe-discounts#14]
Unfortunally the script stopped working for me few days ago :/
Thats the output from 403 Branch:

>   File "Python\Python311\Lib\site-packages\requests\models.py", line `971`, in json
>     return complexjson.loads(self.text, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "Python\Python311\Lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "Python\Python311\Lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
> 
>  raise JSONDecodeError("Expecting value", s, err.value) from None
> 
> 
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
>   File "rewe_discounts.py", line 194, in <module>
>     data = scraper.get(url).json()
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> FAIL: Unknown error while fetching discounts from https://mobile-api.rewe.de/api/v3/all-offers?marketCode=562286, maybe a typo or the server rejected the request.

Upon opening the link  https://mobile-api.rewe.de/api/v3/all-offers?marketCode=562286 manuelly inside my browser it works just fine. Rewe must have improved their IT Skills recently😁 
Doesnt necessarily look like an IP block for me.
I've been using the script for a relatively long time, really great work, too bad it doesn't work for me now.

**Comment by foo-git** [comment]
I just tested the script on my machine, and I also get the same error. Finally I can reproduce it and hopefully fix it :)
I'll try using some other scraping/request methods to access the page. I'll let you know when I've succeeded.

**Comment by foo-git** [comment]
Using `requests` with an user agent instead of `cloudscraper` gives an error message hinting to an IP block. But using Firefox I can still access the url. So it's not an IP ban.

<h1>Access denied</h1>
  <p>You do not have access to mobile-api.rewe.de.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
  <ul class="cferror_details">
    <li>Ray ID: redacted</li>
    <li>Timestamp: 2023-06-09 06:00:49 UTC</li>
    <li>Your IP address: redacted</li>
    <li class="XXX_no_wrap_overflow_hidden">Requested URL: mobile-api.rewe.de/api/v3/all-offers?marketCode=562286 </li>
    <li>Error reference number: 1020</li>
    <li>Server ID: FL_100F55</li>
    <li>User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36</li>
  </ul>

**Comment by foo-git** [comment]
Using a browser-based request method like `playwright` works, I can access the API. This however is severly overblown dependency-wise. I'll try to to find a smaller working solution.

**Comment by foo-git** [comment]
@Nerbry72: I updated the `cloudscraper` dependency to 1.2.69 and (by coincidence?) it fixed the 403 error, I can access the url as usual. Please check if your package is also up-to-date.

**Comment by Nerbry72** [comment]
@foo-git Downgraded from  `cloudscraper-1.2.71` to 1.2.69 worked for me! Thanks for the quick help :D

**Comment by foo-git** [comment]
This raises just a few eyebrows and hairs on my neck. [Relevant xkcd](https://xkcd.com/2347/).

**Comment by FaserF** [comment]
Just to let you know, I just wanted to downgrade the cloudscaper dependency within my Homeassistant Addon too, but randomly it started working again.
1.2.69 should somewhen stop working, since 1.2.71 introduced newer ssl context proto version methods.

**Comment by foo-git** [comment]
Thanks for your valuable feedback.
So right now I'm not sure if pinning the version to 1.2.69 helped to solve the issue, or if changes on Cloudflare/Rewe affected the API access. I have a feeling that this issue will pop up again in the future 😕

**Comment by DennisK90** [comment]
Unfortunately it does not work for me, although I have tried the above suggestions. Can somebody give me some tips?

**Comment by foo-git** [comment]
(Hopefully) good new everyone: Based on the contribution of #16 (which seems to have been deleted, but comment got saved in https://github.com/foo-git/rewe-discounts/issues/9#issuecomment-1593708142), I added a second code path which only gets used, if the traditional single-query method fails.

You can find the updated file in the [additional_retrieval_method branch](https://github.com/foo-git/rewe-discounts/tree/additional_retrieval_method).

The output of the markdown file changed slightly, as the category names are not capitalised anymore.

Please test and feedback, otherwise I'll merge it into master in the next few weeks. Earlier with positive feedback 🚀
